Lesson14 try1
koshel-olga/JavaTrainigEpamMoksiakovaO pull request #13
Opened 2021-05-22 05:47 UTC by koshel-olga

2021-05-22 13:45 UTC, tlt-java-courses requested changes

2021-05-22 13:45 UTC, tlt-java-courses commented on javatraining-db/pom.xml
> +        <plugin>
Табы?

2021-05-22 13:45 UTC, tlt-java-courses commented on javatraining-db/pom.xml
>      <dependencies>
Депенды обычно идут перед тегом build

2021-05-22 13:45 UTC, tlt-java-courses commented on javatraining-db/src/main/resources/migrations/master.xml
> +    <include file="src/main/resources/migrations/v1-initdb/javatraining-db-v1-init-cumulative.xml"/>
1. Даный ченжлог должен буть кумулятивным 
2. Обычно его называют database_{название проекта}_changelog.xml

2021-05-22 13:45 UTC, tlt-java-courses commented on javatraining-db/src/main/resources/migrations/v1-initdb/javatraining-db-v1-init-cumulative.xml
> +    <include file="src/main/resources/migrations/v1-initdb/create-table-customer.xml"/>
1. Давай не будем такую глубокую вложенность делать, которая не несет смысла и внесим все ченж сеты в данный ченжлог
2. И переименуем его как-нибудь по понятнее, желательно чтобы содержало версию

2021-05-22 13:45 UTC, tlt-java-courses commented on javatraining-db/src/main/resources/migrations/v1-initdb/create-table-customer.xml
> +        <preConditions onFail="MARK_RAN">
Не уверен что нам нужны прикондишены при первой раскатке скриптов миграции. У нас базы до этого не существовало

2021-05-22 13:45 UTC, tlt-java-courses commented on javatraining-db/src/main/resources/migrations/v1-initdb/create-table-customer.xml
> +    <changeSet id="2021-05-21_create_table_Customer" author="moksiakova">
Автор: Имя_Фамилия

2021-05-22 13:59 UTC, koshel-olga commented on javatraining-db/src/main/resources/migrations/v1-initdb/javatraining-db-v1-init-cumulative.xml
> +    <include file="src/main/resources/migrations/v1-initdb/create-table-customer.xml"/>
Сергей, оставила на каждую таблицу свой файл, мне как-то удобнее так...

2021-05-23 20:07 UTC, tlt-java-courses approved these changes

2021-05-23 20:07 UTC, merged